version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./path/to/application.properties:/path/to/application.properties
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DATASOURCE_URL
      - POSTGRES_USER=$DATASOURCE_USERNAME
      - POSTGRES_PASSWORD=$DATASOURCE_PASSWORD
    ports:
      - 5432:5432

  telegram-bot:
    image: telegram-bot
    env_file: ./.env
    environment:
      - TELEGRAM_BOT_NAME=$BOT_NAME
      - TELEGRAM_BOT_TOKEN=$BOT_TOKEN